FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge

# Install dependencies
RUN apt-get update && \
    apt-get install -y wget unzip clang libssl-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Set clang as the default compiler
ENV CC=clang
ENV CXX=clang++

# Download and install the latest protoc compiler (arm64 version)
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-aarch_64.zip -O protoc.zip && \
    unzip protoc.zip -d /usr/local && \
    rm protoc.zip

COPY proto/ ../../proto
