FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge

# Install dependencies for building vendored OpenSSL
RUN apt-get update && \
    apt-get install -y wget unzip clang pkg-config perl perl-modules make && \
    rm -rf /var/lib/apt/lists/*

# Set clang as the default compiler
#https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189
ENV CC=clang
ENV CXX=clang++

# Download and install the latest protoc compiler
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip -O protoc.zip && \
    unzip protoc.zip -d /usr/local && \
    rm protoc.zip

# Copy proto files
COPY proto/ /proto/
