[package]
name = "coordinator"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1.0", features = ["full"] }
quinn = "0.10.2"
tokio-util = { version = "0.6", features = ["io"] }
russh = "0.44.0-beta.2"
russh-keys = "0.44.0-beta.2"
async-trait = "0.1.80"
env_logger = "0.10"
anyhow = "1.0.86"
log = "0.4"
rand = { version = "0.8", features = ["std"] }

clap = { version = "4.5.6", features = ["derive"] }
url = "2.5.0"
rustls = { version = "0.21.12", features = ["quic","dangerous_configuration"] }
rustls-pemfile = "2.1.2"
rcgen = "0.12.1"

log4rs = "1.2.0"
serde = "1.0.203"
toml = "0.8.14"
bytes = "1.6.0"
serde_json = "1.0.118"



[dependencies.uuid]
version = "1.9.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
