// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/passkey/auth/start": {
    params: {};
  };
  "/sign/start": {
    params: {};
  };
  "/sign/finish": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/register" | "/login" | "/dashboard" | "/passkey/auth/start" | "/sign/start" | "/sign/finish";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/passkey_auth_start.tsx": {
    id: "routes/passkey_auth_start";
    page: "/passkey/auth/start";
  };
  "routes/device_sign_start.tsx": {
    id: "routes/device_sign_start";
    page: "/sign/start";
  };
  "routes/device_sign_finish.tsx": {
    id: "routes/device_sign_finish";
    page: "/sign/finish";
  };
};