[target.x86_64-unknown-linux-gnu]
image = "x86_64-unknown-linux-gnu-protoc"

[target.aarch64-unknown-linux-gnu]
image = "aarch64-unknown-linux-gnu-protoc"

[target.i686-unknown-linux-gnu]
image = "i686-unknown-linux-gnu-protoc"
